
PREFIX : <http://www.semanticweb.org/TassonomiaAristotelicaFormalizzata#>
SELECT ?differenza ?asse
WHERE {
  :Cervo :CaratterizzatoDa ?differenza .
  ?differenza :AppartieneAsse ?asse .}




SELECT ?animale ?parte ?funzione
WHERE {
  ?animale a :Animale ;
           :HaParteOsservata ?parte .
  ?parte :HaFunzione ?funzione .}




SELECT ?asse ?differenza
WHERE {
  :Cetaceo :CaratterizzatoDa ?differenza .
  ?differenza :AppartieneAsse ?asse .}



SELECT ?differenza (COUNT(?animale) AS ?numeroAnimali)
WHERE {
  ?animale a ari:Animale ;
           ari:CaratterizzatoDa ?differenza .}
GROUP BY ?differenza

